flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/haskell-works/hw-kafka-client
    commit: ee119487711b5b0682ec37f6321020cca667ea37
  extra-dep: true
resolver: lts-13.1
